require:
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

RSpec/BlockLength:
  Max: 20

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
